### ISSUE TITLE
[Backend] Readling log config from filesystem

### ISSUE THREAD

**Issue by sundriver** [atogov/RAM#84]
https://www.npmjs.com/package/winston-config

at the moment it is hard coded in server.ts

**Comment by claustral** [comment]
I note that Winston supports AMQP (such as RabbitMQ) - to me this seems like a good option for audit logging (because it uses reliable messaging).  I realise that at the moment you are probably interested in application event logging but I'd be interested in your comments on using Winston for audit logging.

**Comment by sundriver** [comment]
good point, is there any existing message queue we can push the logs to ?

**Comment by claustral** [comment]
what I'm thinking is you setup a local RabbitMQ, and write a little service to consume messages from the queue and write them to a MongoDB database.  The producer has some cheap I/o to do and keeps going, knowing that the message was safely delivered to the queue, and the consumer service has a bit more work to do (a fairly standard pattern) and does not remove the message from the queue until it has completed its unit of work.  Then the plan would be to see if we can route messages from RabbitMQ to WebSphere MQ in order to integrate with the "Common Audit Logging" solution.  The service could be re-worked to support writing to WMQ in the format that CAL needs instead of MongoDB, or there is something nice that reads from the queue that also acts as an AMQP Client for MQ.  I was just having a quick look at this: https://www.ibm.com/developerworks/community/blogs/messaging/entry/MQ_support_for_MQ_Light_released_in_8_0_0_4?lang=en_uk
